name: My App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - run: pnpm install

      - run: pnpm run test

      - run: docker build -t my-app .

      - run: docker push my-app